#!/bin/bash
#
# all commands that start with SBATCH contain commands that are just used by SLURM for scheduling
#################
# set a job name
#SBATCH --job-name=RGL
#################
# a file for job output, you can check job progress
#SBATCH --output=output_v2.out
#################
# a file for errors from the job
#SBATCH --error=error_v2.err
#################
# time you think you need; default is one hour
# in minutes
# In this case, hh:mm:ss, select whatever time you want, the less you ask for the # faster your job will run.
# Default is one hour, this example will run in  less that 5 minutes.
#SBATCH --time=1-23:55:00
#################
# --gres will give you one GPU, you can ask for more, up to 4 (or how ever many are on the node/card)
#SBATCH --gres gpu:1
#SBATCH --constraint=gpu_12gb
# We are submitting to the batch partition
#SBATCH --qos=batch
#################
#number of nodes you are requesting
#SBATCH --nodes=1
#################
#memory per node; default is 4000 MB per CPU
#SBATCH --mem=12000
#SBATCH --cpus-per-task=8
#################
# Have SLURM send you an email when the job ends or fails, careful, the email could end up in your clutter folder
#SBATCH --mail-type=END,FAIL # notifications for job done & fail
#SBATCH --mail-user=sk7685@nyu.edu

module load python-3
module load cuda-9.0
#virtualenv ~/tf_env
source ~/tf_new/bin/activate tf_new
srun python3 train.py -N 201 -l 0.000001 -v RGL
srun python3 train.py -N 201 -l 0.000005 -b 32 -v RGL
srun python3 train.py -N 401 -l 0.00001 -b 32 -v RGL
srun python3 train.py -N 401 -l 0.00003 -b 64 -v RGL
srun python3 train.py -N 1001 -l 0.0001 -b 64 -v RGL
srun python3 train.py -N 1000000 -l 0.00001 -b 64 -v RGL
